version: '3.8'
services:
  ecommerce:
    image: node:13.12.0-alpine
    volumes:
      - type: bind
        source: ./
        target: /app
      - type: volume
        source: nodemodules 
        target: /app/node_modules
        volume:
          nocopy: true
    working_dir: /app
    command: node dist/backend/app.js
    ports: 
      - '3000:8080'
    env_file: .env
volumes:
  nodemodules:
